"""create generated resumes table

Revision ID: 3833ffc4b5fb
Revises: c9e32425a318
Create Date: 2026-08-15 14:12:06.777873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3833ffc4b5fb'
down_revision: Union[str, Sequence[str], None] = 'c9e32425a318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_resumes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('resume_id', sa.String(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=False),
    sa.Column('generated_resume', sa.JSON(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_resumes_resume_id'), 'generated_resumes', ['resume_id'], unique=False)
    op.create_index(op.f('ix_generated_resumes_user_id'), 'generated_resumes', ['user_id'], unique=False)
    
    op.drop_constraint(op.f('ats_analyses_resume_id_fkey'), 'ats_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'ats_analyses', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ats_analyses', type_='foreignkey')
    op.create_foreign_key(op.f('ats_analyses_resume_id_fkey'), 'ats_analyses', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    
    op.drop_index(op.f('ix_generated_resumes_user_id'), table_name='generated_resumes')
    op.drop_index(op.f('ix_generated_resumes_resume_id'), table_name='generated_resumes')
    op.drop_table('generated_resumes')
    # ### end Alembic commands ###
