"""Create resumes table

Revision ID: a42130ca64d4
Revises: ec042cc8fe49
Create Date: 2026-08-02 18:49:05.077812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42130ca64d4'
down_revision: Union[str, Sequence[str], None] = 'ec042cc8fe49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('parsing_status', sa.String(length=30), nullable=False))
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('resumes', 'extracted_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'extracted_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resumes', 'parsing_status')
    op.drop_column('resumes', 'ats_score')
    # ### end Alembic commands ###
